apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-user


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-user
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50